services:
  # Our PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "9001:9001"
    restart: always
    environment:
      POSTGRES_PASSWORD: theGoat!

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080